/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiectsgbd;

import java.sql.*;
import java.awt.*;

/**
 *
 * @author Alin
 */
public class CreazaTabel extends javax.swing.JFrame {

    /**
     * Creates new form CreazaTabel
     */
    public CreazaTabel() {

        initComponents();
        GolireJ();
    }
    private Connection connect = null;
    private Statement statement = null;
    String Final = "";
    String Final2 = "";
    String Final3 = "";
    String Final4 = "";
    String Final5 = "";
    private String gsi = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCBSelecteazaBaza = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jTFNumeTabel = new javax.swing.JTextField();
        jButonCreazaTabel = new javax.swing.JButton();
        jButonIesire = new javax.swing.JButton();
        jButonInapoi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        jTFHost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFPassword = new javax.swing.JTextField();
        JButonIncarca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel16 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jCBUQ1 = new javax.swing.JCheckBox();
        jCBNN1 = new javax.swing.JCheckBox();
        jCBPK1 = new javax.swing.JCheckBox();
        jCB1 = new javax.swing.JComboBox();
        jTFN1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jCBUQ2 = new javax.swing.JCheckBox();
        jCBNN2 = new javax.swing.JCheckBox();
        jCBPK2 = new javax.swing.JCheckBox();
        jCB2 = new javax.swing.JComboBox();
        jTFN2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jCBUQ3 = new javax.swing.JCheckBox();
        jCBNN3 = new javax.swing.JCheckBox();
        jCBPK3 = new javax.swing.JCheckBox();
        jCB3 = new javax.swing.JComboBox();
        jTFN3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jCBUQ4 = new javax.swing.JCheckBox();
        jCBNN4 = new javax.swing.JCheckBox();
        jCBPK4 = new javax.swing.JCheckBox();
        jCB4 = new javax.swing.JComboBox();
        jTFN4 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jCBUQ5 = new javax.swing.JCheckBox();
        jCBNN5 = new javax.swing.JCheckBox();
        jCBPK5 = new javax.swing.JCheckBox();
        jCB5 = new javax.swing.JComboBox();
        jTFN5 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jCBUQ6 = new javax.swing.JCheckBox();
        jCBNN6 = new javax.swing.JCheckBox();
        jCBPK6 = new javax.swing.JCheckBox();
        jCB6 = new javax.swing.JComboBox();
        jTFN6 = new javax.swing.JTextField();
        jPanelNrCol = new javax.swing.JPanel();
        jCBNrCol = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Creaza tabel");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecteaza baza de date"));

        jCBSelecteazaBaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSelecteazaBazaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCBSelecteazaBaza, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCBSelecteazaBaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nume Tabel"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTFNumeTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTFNumeTabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButonCreazaTabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButonCreazaTabel.setText("Creaza Tabel");
        jButonCreazaTabel.setMaximumSize(new java.awt.Dimension(73, 25));
        jButonCreazaTabel.setMinimumSize(new java.awt.Dimension(73, 25));
        jButonCreazaTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonCreazaTabelActionPerformed(evt);
            }
        });

        jButonIesire.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButonIesire.setText("Iesire");
        jButonIesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonIesireActionPerformed(evt);
            }
        });

        jButonInapoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButonInapoi.setText("Inapoi");
        jButonInapoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonInapoiActionPerformed(evt);
            }
        });

        jLabel5.setText("User");

        jLabel6.setText("Host");

        jTFUser.setText("root");

        jTFHost.setText("localhost");

        jLabel7.setText("Password");

        JButonIncarca.setText("Incarca");
        JButonIncarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButonIncarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFHost)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(JButonIncarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 112, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JButonIncarca)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jCBUQ1.setText("UQ");
        jCBUQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUQ1(evt);
            }
        });

        jCBNN1.setText("NN");

        jCBPK1.setText("PK");
        jCBPK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPK1(evt);
            }
        });

        jCB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT", "VARCHAR", "DATE" }));
        jCB1.setSelectedIndex(-1);
        jCB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jCB1, 0, 189, Short.MAX_VALUE)
                .addGap(35, 35, 35)
                .addComponent(jCBPK1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBNN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUQ1)
                .addGap(47, 47, 47))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBUQ1)
                    .addComponent(jCBNN1)
                    .addComponent(jCBPK1)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFN1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nume Coloane");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tip");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Atribute");

        jCBUQ2.setText("UQ");
        jCBUQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUQ2(evt);
            }
        });

        jCBNN2.setText("NN");

        jCBPK2.setText("PK");
        jCBPK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPK2(evt);
            }
        });

        jCB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT", "VARCHAR", "DATE" }));
        jCB2.setSelectedIndex(-1);
        jCB2.setToolTipText("");
        jCB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jCB2, 0, 189, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(jCBPK2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBNN2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUQ2)
                .addGap(43, 43, 43))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBUQ2)
                    .addComponent(jCBNN2)
                    .addComponent(jCBPK2)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFN2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jCBUQ3.setText("UQ");
        jCBUQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUQ3(evt);
            }
        });

        jCBNN3.setText("NN");

        jCBPK3.setText("PK");
        jCBPK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPK3(evt);
            }
        });

        jCB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT", "VARCHAR", "DATE" }));
        jCB3.setSelectedIndex(-1);
        jCB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFN3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jCB3, 0, 189, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(jCBPK3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBNN3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUQ3)
                .addGap(42, 42, 42))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFN3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBUQ3)
                            .addComponent(jCBNN3)
                            .addComponent(jCBPK3)
                            .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(76, 76, 76))
        );

        jCBUQ4.setText("UQ");
        jCBUQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUQ4(evt);
            }
        });

        jCBNN4.setText("NN");

        jCBPK4.setText("PK");
        jCBPK4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPK4(evt);
            }
        });

        jCB4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT", "VARCHAR", "DATE" }));
        jCB4.setSelectedIndex(-1);
        jCB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFN4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jCB4, 0, 189, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(jCBPK4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBNN4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUQ4)
                .addGap(40, 40, 40))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBUQ4)
                    .addComponent(jCBNN4)
                    .addComponent(jCBPK4)
                    .addComponent(jCB4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFN4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jCBUQ5.setText("UQ");
        jCBUQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUQ5(evt);
            }
        });

        jCBNN5.setText("NN");

        jCBPK5.setText("PK");
        jCBPK5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPK5(evt);
            }
        });

        jCB5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT", "VARCHAR", "DATE" }));
        jCB5.setSelectedIndex(-1);
        jCB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFN5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jCB5, 0, 189, Short.MAX_VALUE)
                .addGap(41, 41, 41)
                .addComponent(jCBPK5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBNN5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBUQ5)
                .addGap(37, 37, 37))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBUQ5)
                    .addComponent(jCBNN5)
                    .addComponent(jCBPK5)
                    .addComponent(jCB5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFN5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        jCBUQ6.setText("UQ");
        jCBUQ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUQ6(evt);
            }
        });

        jCBNN6.setText("NN");

        jCBPK6.setText("PK");
        jCBPK6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPK6(evt);
            }
        });

        jCB6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INT", "VARCHAR", "DATE" }));
        jCB6.setSelectedIndex(-1);
        jCB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCB6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTFN6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jCB6, 0, 189, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addComponent(jCBPK6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBNN6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCBUQ6)
                .addGap(35, 35, 35))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBUQ6)
                    .addComponent(jCBNN6)
                    .addComponent(jCBPK6)
                    .addComponent(jCB6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFN6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel16);

        jPanelNrCol.setBorder(javax.swing.BorderFactory.createTitledBorder("Numar de coloane"));

        jCBNrCol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        jCBNrCol.setSelectedIndex(-1);
        jCBNrCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNrColActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNrColLayout = new javax.swing.GroupLayout(jPanelNrCol);
        jPanelNrCol.setLayout(jPanelNrColLayout);
        jPanelNrColLayout.setHorizontalGroup(
            jPanelNrColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNrColLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBNrCol, 0, 181, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNrColLayout.setVerticalGroup(
            jPanelNrColLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNrColLayout.createSequentialGroup()
                .addComponent(jCBNrCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, 105)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButonCreazaTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(jButonIesire, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButonInapoi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jPanelNrCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNrCol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButonCreazaTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButonIesire, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButonInapoi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButonIesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonIesireActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButonIesireActionPerformed

    private void jButonInapoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonInapoiActionPerformed
        // TODO add your handling code here:
        PaginaPrincipala pp = new PaginaPrincipala();
        pp.setVisible(true);
        pp.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(false);
    }//GEN-LAST:event_jButonInapoiActionPerformed

    private void JButonIncarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButonIncarcaActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:mysql://" + jTFHost.getText();
        String user = jTFUser.getText();
        String password = jTFPassword.getText();
        try {

            connect = DriverManager.getConnection(url, user, password);
            statement = connect.createStatement();
            System.out.println("Connected");
        } catch (Exception e) {
            System.out.println(e);
        }
        jCBSelecteazaBaza.removeAllItems();
        try {
            DatabaseMetaData dbmd = connect.getMetaData();
            String[] types = {"TABLE"};
            ResultSet rs = connect.getMetaData().getTables(null, null, "%", types);

            while (rs.next()) {
                jCBSelecteazaBaza.addItem(rs.getString("TABLE_CAT"));
            }
            rs.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_JButonIncarcaActionPerformed

    private void jCBNrColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNrColActionPerformed
        // TODO add your handling code here:
        int index = jCBNrCol.getSelectedIndex();
        if (index == 0) {
            jPanel16.setVisible(true);
            jPanel15.setVisible(true);
            jPanel6.setVisible(false);
            jPanel8.setVisible(false);
            jPanel7.setVisible(false);
            jPanel9.setVisible(false);
            jPanel10.setVisible(false);
        } else if (index == 1) {
            jPanel16.setVisible(true);
            jPanel15.setVisible(true);
            jPanel6.setVisible(true);
            jPanel8.setVisible(false);
            jPanel7.setVisible(false);
            jPanel9.setVisible(false);
            jPanel10.setVisible(false);
        } else if (index == 2) {
            jPanel16.setVisible(true);
            jPanel15.setVisible(true);
            jPanel6.setVisible(true);
            jPanel8.setVisible(true);
            jPanel7.setVisible(false);
            jPanel9.setVisible(false);
            jPanel10.setVisible(false);
        } else if (index == 3) {
            jPanel16.setVisible(true);
            jPanel15.setVisible(true);
            jPanel6.setVisible(true);
            jPanel8.setVisible(true);
            jPanel7.setVisible(true);
            jPanel9.setVisible(false);
            jPanel10.setVisible(false);
        } else if (index == 4) {
            jPanel16.setVisible(true);
            jPanel15.setVisible(true);
            jPanel6.setVisible(true);
            jPanel8.setVisible(true);
            jPanel7.setVisible(true);
            jPanel9.setVisible(true);
            jPanel10.setVisible(false);
        } else if (index == 5) {
            jPanel16.setVisible(true);
            jPanel15.setVisible(true);
            jPanel6.setVisible(true);
            jPanel8.setVisible(true);
            jPanel7.setVisible(true);
            jPanel9.setVisible(true);
            jPanel10.setVisible(true);
        }

    }//GEN-LAST:event_jCBNrColActionPerformed

    private void jButonCreazaTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonCreazaTabelActionPerformed
        // TODO add your handling code here:
        String standard = "CREATE TABLE " + jTFNumeTabel.getText() + "(";
        String url = "jdbc:mysql://" + jTFHost.getText() + "/" + gsi;
        String user = jTFUser.getText();
        String password = jTFPassword.getText();
        try {

            connect = DriverManager.getConnection(url, user, password);
            statement = connect.createStatement();
            System.out.println("Connected");
            if (jCBNrCol.getSelectedIndex() == 0) {
                Col1(standard);
            } else if (jCBNrCol.getSelectedIndex() == 1) {
                Col1F();
                Col2();
            } else if (jCBNrCol.getSelectedIndex() == 2) {
                Col1F();
                Col2F();
                Col3();
            } else if (jCBNrCol.getSelectedIndex() == 3) {
                Col1F();
                Col2F();
                Col3F();
                Col4();
            } else if (jCBNrCol.getSelectedIndex() == 4) {
                Col1F();
                Col2F();
                Col3F();
                Col4F();
                Col5();
            } else if (jCBNrCol.getSelectedIndex() == 5) {
                Col1F();
                Col2F();
                Col3F();
                Col4F();
                Col5F();
                Col6();
            }
            statement.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        Golire();


    }//GEN-LAST:event_jButonCreazaTabelActionPerformed

    private void CBPK1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPK1
        // TODO add your handling code here:int index = jCB1.getSelectedIndex();
        if (jCBPK1.isSelected() == true) {

            jCB1.setEnabled(false);
            jCBUQ1.setEnabled(false);
            jCBNN1.setSelected(false);
            jCBNN1.setEnabled(false);
            jCBPK2.setEnabled(false);
            jCBPK3.setEnabled(false);
            jCBPK4.setEnabled(false);
            jCBPK5.setEnabled(false);
            jCBPK6.setEnabled(false);
        } else {

            jCB1.setEnabled(true);
            jCBUQ1.setEnabled(true);
            jCBNN1.setSelected(false);
            jCBNN1.setEnabled(true);
            jCBPK2.setEnabled(true);
            jCBPK3.setEnabled(true);
            jCBPK4.setEnabled(true);
            jCBPK5.setEnabled(true);
            jCBPK6.setEnabled(true);
        }

    }//GEN-LAST:event_CBPK1

    private void CBPK2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPK2
        // TODO add your handling code here:
        int index = jCB2.getSelectedIndex();
        if (jCBPK2.isSelected() == true) {
            index = 0;
            jCB2.setEnabled(false);
            jCBUQ2.setEnabled(false);
            jCBNN2.setEnabled(false);
            jCBPK1.setEnabled(false);
            jCBPK3.setEnabled(false);
            jCBPK4.setEnabled(false);
            jCBPK5.setEnabled(false);
            jCBPK6.setEnabled(false);
        } else {
            index = -1;
            jCB2.setEnabled(true);
            jCBUQ2.setEnabled(true);
            jCBNN2.setEnabled(true);
            jCBPK1.setEnabled(true);
            jCBPK3.setEnabled(true);
            jCBPK4.setEnabled(true);
            jCBPK5.setEnabled(true);
            jCBPK6.setEnabled(true);
        }
    }//GEN-LAST:event_CBPK2

    private void CBPK3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPK3
        // TODO add your handling code here:
        int index = jCB3.getSelectedIndex();
        if (jCBPK3.isSelected() == true) {
            index = 0;
            jCB3.setEnabled(false);
            jCBUQ3.setEnabled(false);
            jCBNN3.setEnabled(false);
            jCBPK1.setEnabled(false);
            jCBPK2.setEnabled(false);
            jCBPK4.setEnabled(false);
            jCBPK5.setEnabled(false);
            jCBPK6.setEnabled(false);
        } else {
            index = -1;
            jCB3.setEnabled(true);
            jCBUQ3.setEnabled(true);
            jCBNN3.setEnabled(true);
            jCBPK1.setEnabled(true);
            jCBPK2.setEnabled(true);
            jCBPK4.setEnabled(true);
            jCBPK5.setEnabled(true);
            jCBPK6.setEnabled(true);
        }
    }//GEN-LAST:event_CBPK3

    private void CBPK4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPK4
        // TODO add your handling code here:
        int index = jCB4.getSelectedIndex();
        if (jCBPK4.isSelected() == true) {
            index = 0;
            jCB4.setEnabled(false);
            jCBUQ4.setEnabled(false);
            jCBNN4.setEnabled(false);
            jCBPK1.setEnabled(false);
            jCBPK2.setEnabled(false);
            jCBPK3.setEnabled(false);
            jCBPK5.setEnabled(false);
            jCBPK6.setEnabled(false);
        } else {
            index = -1;
            jCB4.setEnabled(true);
            jCBUQ4.setEnabled(true);
            jCBNN4.setEnabled(true);
            jCBPK1.setEnabled(true);
            jCBPK2.setEnabled(true);
            jCBPK3.setEnabled(true);
            jCBPK5.setEnabled(true);
            jCBPK6.setEnabled(true);
        }
    }//GEN-LAST:event_CBPK4

    private void CBPK5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPK5
        // TODO add your handling code here:
        int index = jCB5.getSelectedIndex();
        if (jCBPK5.isSelected() == true) {
            index = 0;
            jCB5.setEnabled(false);
            jCBUQ5.setEnabled(false);
            jCBNN5.setEnabled(false);
            jCBPK1.setEnabled(false);
            jCBPK2.setEnabled(false);
            jCBPK3.setEnabled(false);
            jCBPK4.setEnabled(false);
            jCBPK6.setEnabled(false);
        } else {
            index = -1;
            jCB5.setEnabled(true);
            jCBUQ5.setEnabled(true);
            jCBNN5.setEnabled(true);
            jCBPK1.setEnabled(true);
            jCBPK2.setEnabled(true);
            jCBPK3.setEnabled(true);
            jCBPK4.setEnabled(true);
            jCBPK6.setEnabled(true);
        }
    }//GEN-LAST:event_CBPK5

    private void CBPK6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPK6
        // TODO add your handling code here:
        int index = jCB6.getSelectedIndex();
        if (jCBPK6.isSelected() == true) {
            index = 0;
            jCB6.setEnabled(false);
            jCBUQ6.setEnabled(false);
            jCBNN6.setEnabled(false);
            jCBPK1.setEnabled(false);
            jCBPK2.setEnabled(false);
            jCBPK3.setEnabled(false);
            jCBPK4.setEnabled(false);
            jCBPK5.setEnabled(false);
        } else {
            index = -1;
            jCB6.setEnabled(true);
            jCBUQ6.setEnabled(true);
            jCBNN6.setEnabled(true);
            jCBPK1.setEnabled(true);
            jCBPK2.setEnabled(true);
            jCBPK3.setEnabled(true);
            jCBPK4.setEnabled(true);
            jCBPK5.setEnabled(true);
        }
    }//GEN-LAST:event_CBPK6

    private void CBUQ1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUQ1
        // TODO add your handling code here:
        if (jCBUQ1.isSelected() == true) {
            jCBNN1.setEnabled(false);
        } else {
            jCBNN1.setEnabled(true);
        }
    }//GEN-LAST:event_CBUQ1

    private void CBUQ2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUQ2
        // TODO add your handling code here:
        if (jCBUQ2.isSelected() == true) {
            jCBNN2.setEnabled(false);
        } else {
            jCBNN2.setEnabled(true);
        }
    }//GEN-LAST:event_CBUQ2

    private void CBUQ3(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUQ3
        // TODO add your handling code here:
        if (jCBUQ3.isSelected() == true) {
            jCBNN3.setEnabled(false);
        } else {
            jCBNN3.setEnabled(true);
        }
    }//GEN-LAST:event_CBUQ3

    private void CBUQ4(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUQ4
        // TODO add your handling code here:
        if (jCBUQ4.isSelected() == true) {
            jCBNN4.setEnabled(false);
        } else {
            jCBNN4.setEnabled(true);
        }
    }//GEN-LAST:event_CBUQ4

    private void CBUQ5(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUQ5
        // TODO add your handling code here:
        if (jCBUQ5.isSelected() == true) {
            jCBNN5.setEnabled(false);
        } else {
            jCBNN5.setEnabled(true);
        }

    }//GEN-LAST:event_CBUQ5

    private void CBUQ6(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUQ6
        // TODO add your handling code here:
        if (jCBUQ6.isSelected() == true) {
            jCBNN6.setEnabled(false);
        } else {
            jCBNN6.setEnabled(true);
        }

    }//GEN-LAST:event_CBUQ6

    private void jCBSelecteazaBazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSelecteazaBazaActionPerformed
        // TODO add your handling code here:

        gsi = jCBSelecteazaBaza.getSelectedItem().toString();
    }//GEN-LAST:event_jCBSelecteazaBazaActionPerformed

    String valoare = "";
    private void jCB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB1ActionPerformed
        // TODO add your handling code here:
        try {
            switch (jCB1.getSelectedItem().toString().trim()) {
                case "INT":
                    valoare = " INT ";
                    break;
                case "VARCHAR":
                    valoare = " VARCHAR(200) ";
                    break;
                case "DATE":
                    valoare = " DATE ";
                    break;

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jCB1ActionPerformed
    String valoare2 = "";
    private void jCB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB2ActionPerformed
        // TODO add your handling code here:
        try {
            switch (jCB2.getSelectedItem().toString().trim()) {
                case "INT":
                    valoare2 = " INT ";
                    break;
                case "VARCHAR":
                    valoare2 = " VARCHAR(200) ";
                    break;
                case "DATE":
                    valoare2 = " DATE ";
                    break;

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jCB2ActionPerformed
    String valoare3 = "";
    private void jCB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB3ActionPerformed
        // TODO add your handling code here:
        try {
            switch (jCB3.getSelectedItem().toString().trim()) {
                case "INT":
                    valoare3 = " INT ";
                    break;
                case "VARCHAR":
                    valoare3 = " VARCHAR(200) ";
                    break;
                case "DATE":
                    valoare3 = " DATE ";
                    break;

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jCB3ActionPerformed
    String valoare4 = "";
    private void jCB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB4ActionPerformed
        // TODO add your handling code here:
        try {
            switch (jCB4.getSelectedItem().toString().trim()) {
                case "INT":
                    valoare4 = " INT ";
                    break;
                case "VARCHAR":
                    valoare4 = " VARCHAR(200) ";
                    break;
                case "DATE":
                    valoare4 = " DATE ";
                    break;

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jCB4ActionPerformed
    String valoare5 = "";
    private void jCB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB5ActionPerformed
        // TODO add your handling code here:
        try {
            switch (jCB5.getSelectedItem().toString().trim()) {
                case "INT":
                    valoare5 = " INT ";
                    break;
                case "VARCHAR":
                    valoare5 = " VARCHAR(200)";
                    break;
                case "DATE":
                    valoare5 = " DATE ";
                    break;

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jCB5ActionPerformed
    String valoare6 = "";
    private void jCB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCB6ActionPerformed
        // TODO add your handling code here:        
        try {
            switch (jCB6.getSelectedItem().toString().trim()) {
                case "INT":
                    valoare6 = " INT ";
                    break;
                case "VARCHAR":
                    valoare6 = " VARCHAR(200)";
                    break;
                case "DATE":
                    valoare6 = " DATE ";
                    break;

            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jCB6ActionPerformed

    

    private void Col1(String s) throws SQLException {
        String PK1;
        PK1 = "CREATE TABLE " + jTFNumeTabel.getText() + "( " + jTFN1.getText() + " INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY)";
        String NN1;
        NN1 = "CREATE TABLE " + jTFNumeTabel.getText() + "( " + jTFN1.getText() + valoare + " NOT NULL )";
        String UQ1;
        UQ1 = "CREATE TABLE " + jTFNumeTabel.getText() + "( " + jTFN1.getText() + valoare + " UNIQUE ) ";
        String standard1;
        standard1 = "CREATE TABLE " + jTFNumeTabel.getText() + "( " + jTFN1.getText() + valoare + " ) ";
        if (jCBPK1.isSelected() == true) {
            statement.executeUpdate(PK1);
        } else if (jCBNN1.isSelected() == true) {
            statement.executeUpdate(NN1);
        } else if (jCBUQ1.isSelected() == true) {
            statement.executeUpdate(UQ1);
        } else {
            statement.execute(standard1);
        }
    }

    private void Col1F() {
        if (jCBPK1.isSelected() == true) {
            Final += jTFN1.getText() + " INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY,";
        } else if (jCBNN1.isSelected() == true) {
            Final += jTFN1.getText() + valoare + "NOT NULL, ";

        } else if (jCBUQ1.isSelected() == true) {
            Final += jTFN1.getText() + valoare + "UNIQUE NOT NULL, ";
        } else {
            Final += jTFN1.getText() + valoare + ",";
        }
        System.out.println(Final);

    }

    private void Col2() throws SQLException {
        String standard2;
        String standard2f;
        standard2 = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + jTFN2.getText() + valoare2 + " ";
        standard2f = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + jTFN2.getText() + valoare2 + ")";
        String PK2;
        PK2 = standard2 + "INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY )";
        String NN2;
        NN2 = standard2 + "NOT NULL )";
        String UQ2;
        UQ2 = standard2 + "UNIQUE NOL NULL )";

        if (jCBPK2.isSelected() == true) {
            statement.executeUpdate(PK2);
        } else if (jCBNN2.isSelected() == true) {
            statement.executeUpdate(NN2);
        } else if (jCBUQ2.isSelected() == true) {
            statement.executeUpdate(UQ2);
        } else {
            statement.executeUpdate(standard2f);
        }
    }
    //private String Final2="";


    private void Col2F() {

        if (jCBPK2.isSelected() == true) {
            Final2 += jTFN2.getText() + "INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY, ";
        } else if (jCBNN2.isSelected() == true) {
            Final2 += jTFN2.getText() + " " + valoare2 + " NOT NULL, ";

        } else if (jCBUQ2.isSelected() == true) {
            Final2 += jTFN2.getText() + valoare2 + " UNIQUE NOT NULL, ";
        } else {
            Final2 += jTFN2.getText() + valoare2 + ", ";
        }
        System.out.println(Final2);
    }

    private void Col3() throws SQLException {
        String standard3;
        String standard3f;
        String comanda = jTFN3.getText() + valoare3;
        standard3 = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final2 + jTFN3.getText() + valoare3 + " ";
        standard3f = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + Final2 + jTFN3.getText() + valoare3 + ")";
        String PK3;
        PK3 = standard3 + "INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY )";
        String NN3;
        NN3 = standard3 + "NOT NULL )";
        String UQ3;
        UQ3 = standard3 + "UNIQUE NOL NULL )";

        if (jCBPK3.isSelected() == true) {
            statement.executeUpdate(PK3);
        } else if (jCBNN3.isSelected() == true) {
            statement.executeUpdate(NN3);
        } else if (jCBUQ3.isSelected() == true) {
            statement.executeUpdate(UQ3);
        } else {
            statement.executeUpdate(standard3f);
        }
    }

    private void Col3F() throws SQLException {

        if (jCBPK3.isSelected() == true) {
            Final3 += jTFN3.getText() + " INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY,";
        } else if (jCBNN3.isSelected() == true) {
            Final3 += jTFN3.getText() + valoare3 + " NOT NULL, ";

        } else if (jCBUQ3.isSelected() == true) {
            Final3 += jTFN3.getText() + valoare3 + " UNIQUE NOT NULL, ";
        } else {
            Final3 += jTFN3.getText() + valoare3 + ",";
        }
    }

    private void Col4() throws SQLException {
        String standard4;
        String standard4f;
        standard4f = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + Final2 + Final3 + jTFN4.getText() + valoare4 + ")";
        standard4 = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + Final2 + Final3 + jTFN4.getText() + valoare4 + " ";
        String PK4;
        PK4 = standard4 + "INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY)";
        String NN4;
        NN4 = standard4 + " NOT NULL)";
        String UQ4;
        UQ4 = standard4 + " UNIQUE)";

        if (jCBPK4.isSelected() == true) {
            statement.executeUpdate(PK4);
        } else if (jCBNN4.isSelected() == true) {
            statement.executeUpdate(NN4);
        } else if (jCBUQ4.isSelected() == true) {
            statement.executeUpdate(UQ4);
        } else {
            statement.executeUpdate(standard4f);
        }
    }

    private void Col4F() throws SQLException {

        if (jCBPK4.isSelected() == true) {
            Final4 += jTFN4.getText() + " INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY,";
        } else if (jCBNN4.isSelected() == true) {
            Final4 += jTFN4.getText() + valoare4 + " NOT NULL, ";

        } else if (jCBUQ4.isSelected() == true) {
            Final4 += jTFN4.getText() + valoare4 + " UNIQUE NOT NULL, ";
        } else {
            Final4 += jTFN4.getText() + valoare4 + ",";
        }
    }

    private void Col5() throws SQLException {
        String standard5f;
        standard5f = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + Final2 + Final3 + Final4 + jTFN5.getText() + valoare5 + ")";
        String standard5;
        standard5 = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + Final2 + Final3 + Final4 + jTFN5.getText() + valoare5 + " ";
        String PK5;
        PK5 = standard5 + " INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY)";
        String NN5;
        NN5 = standard5 + " NOT NULL)";
        String UQ5;
        UQ5 = standard5 + " UNIQUE)";

        if (jCBPK5.isSelected() == true) {
            statement.executeUpdate(PK5);
        } else if (jCBNN5.isSelected() == true) {
            statement.executeUpdate(NN5);
        } else if (jCBUQ5.isSelected() == true) {
            statement.executeUpdate(UQ5);
        } else {
            statement.executeUpdate(standard5f);
        }
    }

    private void Col5F() throws SQLException {

        if (jCBPK5.isSelected() == true) {
            Final5 += jTFN5.getText() + " INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY,";
        } else if (jCBNN5.isSelected() == true) {
            Final5 += jTFN5.getText() + jCB5.getSelectedItem().toString() + " NOT NULL, ";

        } else if (jCBUQ5.isSelected() == true) {
            Final5 += jTFN5.getText() + jCB5.getSelectedItem().toString() + " UNIQUE NOT NULL, ";
        } else {
            Final5 += jTFN5.getText() + jCB5.getSelectedItem().toString() + " ,";
        }
    }

    private void Col6() throws SQLException {
        String standard6f;
        standard6f = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + Final2 + Final3 + Final4+ Final5 + jTFN6.getText() + valoare6 + ")";
        String standard6;
        standard6 = "CREATE TABLE " + jTFNumeTabel.getText() + "(" + Final + Final2 + Final3 + Final4 + Final5 + jTFN6.getText() + valoare6 + " ";
        String PK6;
        PK6 = standard6 + " INT(6) AUTO_INCREMENT NOT NULL PRIMARY KEY)";
        String NN6;
        NN6 = standard6 + "NOT NULL)";
        String UQ6;
        UQ6 = standard6 + "UNIQUE)";

        if (jCBPK6.isSelected() == true) {
            statement.executeUpdate(PK6);
        } else if (jCBNN6.isSelected() == true) {
            statement.executeUpdate(NN6);
        } else if (jCBUQ6.isSelected() == true) {
            statement.executeUpdate(UQ6);
        } else {
            statement.executeUpdate(standard6f);
        }
    }

    private void Golire() {
        jTFNumeTabel.setText("");
        jCBNrCol.setSelectedIndex(-1);
        valoare = "";
        valoare2 = "";
        valoare3 = "";
        valoare4 = "";
        valoare5 = "";
        valoare6 = "";

        Final = "";
        Final2 = "";
        Final3 = "";
        Final4 = "";
        Final5 = "";

        jTFN1.setText("");
        jCB1.setSelectedIndex(-1);
        jCBPK1.setSelected(false);
        jCBNN1.setSelected(false);
        jCBUQ1.setSelected(false);
        jPanel15.setVisible(false);

        jTFN2.setText("");
        jCB2.setSelectedIndex(-1);
        jCBPK2.setSelected(false);
        jCBNN2.setSelected(false);
        jCBUQ2.setSelected(false);
        jPanel6.setVisible(false);

        jTFN3.setText("");
        jCB3.setSelectedIndex(-1);
        jCBPK3.setSelected(false);
        jCBNN3.setSelected(false);
        jCBUQ3.setSelected(false);
        jPanel7.setVisible(false);

        jTFN4.setText("");
        jCB4.setSelectedIndex(-1);
        jCBPK4.setSelected(false);
        jCBNN4.setSelected(false);
        jCBUQ4.setSelected(false);
        jPanel7.setVisible(false);

        jTFN5.setText("");
        jCB5.setSelectedIndex(-1);
        jCBPK5.setSelected(false);
        jCBNN5.setSelected(false);
        jCBUQ5.setSelected(false);
        jPanel8.setVisible(false);

        jTFN6.setText("");
        jCB6.setSelectedIndex(-1);
        jCBPK6.setSelected(false);
        jCBNN6.setSelected(false);
        jCBUQ6.setSelected(false);
        jPanel9.setVisible(false);

    }

    private void GolireJ() {
        jPanel16.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreazaTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreazaTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreazaTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreazaTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CreazaTabel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButonIncarca;
    private javax.swing.JButton jButonCreazaTabel;
    private javax.swing.JButton jButonIesire;
    private javax.swing.JButton jButonInapoi;
    private javax.swing.JComboBox jCB1;
    private javax.swing.JComboBox jCB2;
    private javax.swing.JComboBox jCB3;
    private javax.swing.JComboBox jCB4;
    private javax.swing.JComboBox jCB5;
    private javax.swing.JComboBox jCB6;
    private javax.swing.JCheckBox jCBNN1;
    private javax.swing.JCheckBox jCBNN2;
    private javax.swing.JCheckBox jCBNN3;
    private javax.swing.JCheckBox jCBNN4;
    private javax.swing.JCheckBox jCBNN5;
    private javax.swing.JCheckBox jCBNN6;
    private javax.swing.JComboBox jCBNrCol;
    private javax.swing.JCheckBox jCBPK1;
    private javax.swing.JCheckBox jCBPK2;
    private javax.swing.JCheckBox jCBPK3;
    private javax.swing.JCheckBox jCBPK4;
    private javax.swing.JCheckBox jCBPK5;
    private javax.swing.JCheckBox jCBPK6;
    private javax.swing.JComboBox jCBSelecteazaBaza;
    private javax.swing.JCheckBox jCBUQ1;
    private javax.swing.JCheckBox jCBUQ2;
    private javax.swing.JCheckBox jCBUQ3;
    private javax.swing.JCheckBox jCBUQ4;
    private javax.swing.JCheckBox jCBUQ5;
    private javax.swing.JCheckBox jCBUQ6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    public javax.swing.JPanel jPanel15;
    public javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelNrCol;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFHost;
    private javax.swing.JTextField jTFN1;
    private javax.swing.JTextField jTFN2;
    private javax.swing.JTextField jTFN3;
    private javax.swing.JTextField jTFN4;
    private javax.swing.JTextField jTFN5;
    private javax.swing.JTextField jTFN6;
    private javax.swing.JTextField jTFNumeTabel;
    private javax.swing.JTextField jTFPassword;
    private javax.swing.JTextField jTFUser;
    // End of variables declaration//GEN-END:variables
}
